Add YANG support
SmiteshP/nvim-gps pull request #24
Opened 2021-09-20 05:52 UTC by Hubro

This pull request adds YANG support. My opinion is that for a language like YANG with deeply nested structures and a large amount of node types, using icons to represent the node types is not useful. Instead, this implementation shows the node type name directly. Here is an example:

![image](https://user-images.githubusercontent.com/597206/133961419-93067eee-ca2c-49ae-a473-2a489ef24ecc.png)

If icons should be used for the node types, there would have to be a large amount of different icons and they would have to be specific for YANG to be useful.

2021-09-20 09:25 UTC, SmiteshP commented
Hey! Thanks for the PR! 🎉 

Before I merge this I would like to say that right now this doesn't give any control over the "icons" for the language and is a bit verbose in my opinion.

> If icons should be used for the node types, there would have to be a large amount of different icons and they would have to be specific for YANG to be useful.

The Icons don't exactly need to exactly match their namesake's definition. For example in C++ a namespace isn't a class technically, but is still assigned the class-name capture because it can be thought of one. And in Lua a function assigned to a table's field isn't technically a method but is assigned the method-name. What I mean to say is that to treat the capture types (class-name,  container-name, etc) with a little-bit of a loose definition.

Try to fit as many node types in the existing captures if they make sense. However if something doesn't fit in any type, then I would rather have a new icon for it than to simply spell out the node type.

2021-09-20 09:27 UTC, SmiteshP requested changes
Fit the captures in existing capture types if possible or else make new capture types. And allow for icons to be decided by users.

2021-09-20 19:43 UTC, Hubro commented
I'm not sure if it's possible (or useful) to use the same node type / icon paradigm with YANG as with regular programming languages.

Most **programming languages** have classes, functions and methods, or at least concepts that strongly correlate, like structs in Go. Using icons to represent these is nice, clean and understandable.

Markup languages like HTML and XML are completely different. Trying to reuse the same class/function/method icon paradigm here is impossible. Instead a new node type "tag" should probably be added.

I would argue that YANG matches yet another category of language, it's a deeply nested data modelling language. Basically it's a whole language for describing a database, including relations and validation rules. It's more akin to a JSON schema than a program. Instead of classes and functions it has modules, typedefs, groupings, containers, lists and leafs. None of these concepts map onto the class/function/method paradigm, even with a healthy amount of imagination, so the alternatives I see are:

- Don't use icons at all, but prefix the node type name instead (this is what I did)
- Introduce 4-6 new capture types for YANG's node types. I don't know if these capture types could be reused for any other language, so this felt a lot more noisy to me. The result would be a lot more compact than the current solution though, so I'm not opposed to it. I can update the pull request with this and see what you think?

2021-09-21 04:38 UTC, SmiteshP commented
> Markup languages like HTML and XML are completely different. Trying to reuse the same class/function/method icon paradigm here is impossible. Instead a new node type "tag" should probably be added.

Yep, I agree.

> Introduce 4-6 new capture types for YANG's node types. I don't know if these capture types could be reused for any other language, so this felt a lot more noisy to me. The result would be a lot more compact than the current solution though, so I'm not opposed to it. I can update the pull request with this and see what you think?

I think this would be a much better option. Its fine even if they aren't reused in any other language. If the language doesn't fit the class/function paradigm then its better to create more icons for that language specifically.

2021-10-14 19:08 UTC, Hubro commented
@SmiteshP It doesn't seem like it's possible to set default icons for languages in init.lua:

```lua
local default_config = {
	enabled = true,
	icons = {
		["class-name"] = ' ',
		["function-name"] = ' ',
		["method-name"] = ' ',
		["container-name"] = '⛶ ',
		["tag-name"] = '炙'
	},
	languages = {
		["yang"] = {
			icons = {
				["container-name"] = "X",
				["grouping-name"] = "X",
				["typedef-name"] = "X",
				["list-name"] = "X",
				["leaf-list-name"] = "X",
				["leaf-name"] = "X",
			}
		}
	},
	separator = ' > ',
}
```

Is this supposed to work? :thinking:

2021-10-15 03:55 UTC, SmiteshP commented
> Is this supposed to work?

For this you have to set it in the `configs` table.
```lua
local configs = {
    ["yang"] = with_default_config({
        icons = {
				["container-name"] = "X",
				["grouping-name"] = "X",
				["typedef-name"] = "X",
				["list-name"] = "X",
				["leaf-list-name"] = "X",
				["leaf-name"] = "X",
		}
    })
}
```

I know its a bit unintuitive 😅

2021-10-17 05:46 UTC, SmiteshP commented
> @SmiteshP I want to add a capture for the `tailf:action` keyword, but I'm getting this error:
> 
> > query: invalid node type ...
> 
> ```scheme
> ((statement
> 	(statement_keyword "tailf:action")
> 	(argument) @action-name) @scope-root)
> ```
> 
> Apparently I can't match text nodes that include a colon symbol thinking Do you know any way around this?

I think to you are looking for `#match?` or `#eq?` predicates. You can look at the python queries for example of how to use this. If you are using `#match?` you might need to escape the colon as the match predicate uses regex.

2021-10-19 05:18 UTC, Hubro commented
@SmiteshP Aha, I didn't know that was a thing :smile: 

Here's an example:

```yang
module foo {
  container test {
    tailf:action check-health {
      tailf:actionpoint check-health;

      input {
        // ...
      }

      output {
        // ...
      }
    }
  }
}
```

2022-03-19 14:27 UTC, Hubro commented
@SmiteshP Long time no see :smile: I've been working more with YANG lately, and thus, I'm back to this pull request. I have rebased my changes on top of your master branch.

I am still having issues with matching `tailf:action`. This is the query I'm using:

```
((extension_statement
	(extension_keyword) @keyword (#eq? @keyword "tailf:action")
	(argument) @action-name) @scope-root-2)
```

It appears to be a carbon copy of yours. However, as soon as I add it, the entire GPS line goes empty when I navigate inside of an action :thinking: It's clear that the keyword matching works, because if I change the "tailf:action" text to anything else, the query stops having any effect.

Do I need to do anything more to make queries using `@scope-root-2` work with nvim-gps? Because currently it seems like it breaks it.

2022-03-19 14:55 UTC, Hubro commented
@SmiteshP I updated `get_data()` to allow the transform functions to return `nil`, in which case the capture will be ignored and nothing will be added to the GPS line. It seems to work as it should.

2022-03-19 16:06 UTC, SmiteshP commented
Hey @Hubro !
Glad to see the PR again :)

> @SmiteshP I updated get_data() to allow the transform functions to return nil, in which case the capture will be ignored and nothing will be added to the GPS line. It seems to work as it should.

Ok, this seems like a good solution to the issue of that query.

I wanted to test this PR out, but it seems treesitter highlighting and nvim-gps isn't working for me. Is there any extra steps to add yang support to neovim?
Also it would be very helpful if you could share some dummy yang code for me

2022-03-19 17:48 UTC, Hubro commented
That's strange, it works for me without any extra configuration :thinking:

I assume you have run `:TSInstallFromGrammar yang`?

You can test on this YANG file, for example:

https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-ip@2018-02-22.yang

There are no tailf actions in that file, but you can add one if you want to test that:

```yang
    tailf:action test-action {
      tailf:actionpoint test-action;

      input {
        leaf test {
          type string;
          description "Test leaf";
        }
      }

      output {
        leaf result {
          type string;
          description "Result.";
        }
      }
    }
```

2022-03-19 18:01 UTC, SmiteshP commented
I did run `:TSInstall yang` and also `:TSInstallFromGrammar yang`
But it doesn't seem to work 🤔 
Also TS Playground just shows 'string_fragment'
![Screenshot from 2022-03-19 23-29-01](https://user-images.githubusercontent.com/43147494/159132958-f01ad26d-7e65-4409-bb45-a1ac2ea44f1d.png)

2022-03-19 18:08 UTC, SmiteshP commented
Somehow the treesitter is working with the file you shared, everything seems to be working fine 👍🏽

2022-03-19 18:10 UTC, SmiteshP approved these changes

2022-03-19 18:10 UTC, merged

2022-03-19 18:59 UTC, Hubro commented
> Somehow the treesitter is working with the file you shared, everything seems to be working fine 👍🏽

Ah ok, makes sense. The file you were testing on is not valid YANG, as a YANG file has to start with a module or submodule statement.