C++: Add support for qualified function names and functions returning refs
SmiteshP/nvim-gps pull request #83
Opened 2022-03-27 15:17 UTC by ivan-cukic

- Instead of catching `identifier` as the function name, use a catch-all (`_`) as it also catches qualified names like `llvm::function_name`;
- Adds the support for functions returning references as they have a different tree to functions returning values and pointers.

2022-03-27 15:53 UTC, SmiteshP commented
Thanks for the PR!

Could you share example code snippets of which type of captures are added?

2022-03-27 15:57 UTC, ivan-cukic commented
Sure:

```
Expr *llvm::container(Stmt *loop)
{
    :::
}
```

and

```
const Expr& llvm::containerRef(Stmt *loop)
{
    :::
}
```

2022-03-27 16:04 UTC, SmiteshP commented
Ok

Also, which functions does this query add? 

```
((function_definition
	declarator: (function_declarator
		declarator: (_) @function-name)) @scope-root)
```

2022-03-27 16:08 UTC, ivan-cukic commented
With a normal return value:

```
Expr llvm::container(Stmt *loop)
{
    :::
}
```

`identifier` catches only normal function names, for `something::` it will be `qualified_name` - that is why I changed `identifier` to `_` in all three places.

2022-03-27 16:11 UTC, SmiteshP commented
> With a normal return value:
> 
> ```
> Expr llvm::container(Stmt *loop)
> {
>     :::
> }
> ```
> 
> `identifier` catches only normal function names, for `something::func_name` it will be `qualified_name` - that is why I changed `identifier` to `_` in all three places.

Those are actually captured as `method-names` already. Have a look at the last query.

2022-03-27 16:14 UTC, ivan-cukic commented
Hm, didn't work for me. I'll see to test some more and see what might be the problem.

2022-03-27 16:19 UTC, SmiteshP commented
> Hm, didn't work for me. I'll see to test some more and see what might be the problem.

Make sure to update nvim-treesitter, there have been some breaking changes in cpp parser in past.

2022-03-27 16:24 UTC, SmiteshP commented
> Sure:
> 
> ```
> Expr *llvm::container(Stmt *loop)
> {
>     :::
> }
> ```
> 
> and
> 
> ```
> const Expr& llvm::containerRef(Stmt *loop)
> {
>     :::
> }
> ```

For capturing the first example, we should add the following capture
```scm
((function_definition
	declarator: (pointer_declarator
		declarator: (function_declarator
			declarator: (qualified_identifier) @multi-class-method))) @scope-root)
```

And for the second type of methods
```scm
((function_definition
	declarator: (reference_declarator
		(function_declarator
			declarator: (qualified_identifier) @multi-class-method))) @scope-root)
```

2022-03-27 16:49 UTC, ivan-cukic commented
I wanted to reduce the duplication. I've now realized that the following would add even more:

```
class SomeType::Private {
    void f() { ::: }
};
```

2022-03-27 17:05 UTC, ivan-cukic commented
What do you think about using `[(identifier) {qualified_identifier)] @multi-class-method` everywhere -- gps shows this correctly regardless of whether it is a member or a non-member function? And it would avoid having all these for both `identifier` and `qualified_identifier`.

Also possible: `[(identifier) @function-name (qualified_identifier) @multi-class-method]))` but would be a bit more verbose.

2022-03-27 17:23 UTC, ivan-cukic commented
Or this for full support for value, pointer, reference returning member functions that are also defined inside the class:

`[(identifier) @function-name (qualified_identifier) @multi-class-method (field_identifier) @method-name]`

This would render the current last two matchers unneeded.

2022-03-28 02:21 UTC, SmiteshP commented
> Or this for full support for value, pointer, reference returning member functions that are also defined inside the class:
> 
> `[(identifier) @function-name (qualified_identifier) @multi-class-method (field_identifier) @method-name]`
> 
> This would render the current last two matchers unneeded.

I would not prefer to use the square brackets here, I want to keep the queries separate so that its clear what's being captured (atleast to me)

2022-03-28 02:22 UTC, SmiteshP requested changes
Lets keep the queries for functions and methods seperated for ease of understanding

2022-03-28 03:15 UTC, SmiteshP approved these changes

2022-03-28 03:16 UTC, merged